language: python
cache: pip
python:
  - "3.9"
before_install:
  - sudo apt-add-repository ppa:qameta/allure -y
  - sudo apt-get update
  - sudo apt-get install allure -y
install:
  - pip install -r requirements-test.txt
script:
  - bash ./run-ci.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)