credentials:
  # iCloud drive username
  username: user@test.com
  # iCloud drive password
  password:
settings:
  # Sync interval in seconds
  sync_interval: 300
  # Drive destination
  destination: './drive'
  # verbose
  verbose: false
smtp:
  # If you want to recieve email notifications about expired/missing 2FA credentials then uncomment
  # email: user@test.com
  # password:
  # host: smtp.test.com
  # port: 587
  # If your email provider doesn't handle TLS
  # no_tls: true
filters:
  # File filters to be included in syncing iCloud drive content
  folders:
    - Documents
  file_extensions:
    # File extensions to be included
    - pdf
    - png
    - jpg
    - jpeg
